# Generated by Django 2.2 on 2019-04-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0013_pagocredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocredito',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.infousuario'),
        ),
    ]
