# Generated by Django 2.2 on 2019-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0014_auto_20190414_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='infoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTarjeta', models.IntegerField()),
                ('nombreTitular', models.CharField(max_length=15)),
                ('apellidoTitular', models.CharField(max_length=15)),
                ('fechaExpiración', models.CharField(max_length=5)),
                ('codigoSeguridad', models.IntegerField()),
                ('numeroCuotas', models.IntegerField()),
            ],
        ),
    ]
