# Generated by Django 2.2 on 2019-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0015_infotarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
