# Generated by Django 2.2 on 2019-04-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0018_remove_infotarjeta_numerocuotas'),
        ('homePage', '0018_articuloscomprados'),
    ]

    operations = [
    ]
