# Generated by Django 2.2 on 2019-04-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0019_auto_20190416_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.infoLibro')),
                ('usuarioComprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarioComprador', to='homePage.infousuario')),
                ('usuarioDuenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarioDuenio', to='homePage.infousuario')),
            ],
        ),
    ]
