# Generated by Django 2.2 on 2019-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0020_compradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradores',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
