# Generated by Django 2.2 on 2019-04-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0021_contenidomultimedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('usuarioBen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarioBen', to='homePage.infousuario')),
                ('usuarioDonante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarioDonante', to='homePage.infousuario')),
            ],
        ),
    ]
