# Generated by Django 2.2 on 2019-05-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0024_auto_20190430_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='manualidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.contenidoManualidad'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='articuloManual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.contenidoManualidad'),
        ),
    ]
