# Generated by Django 2.2 on 2019-05-03 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0025_auto_20190502_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloscomprados',
            name='manualidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.contenidoManualidad'),
        ),
        migrations.AddField(
            model_name='compradores',
            name='manualidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.contenidoManualidad'),
        ),
    ]
