# Generated by Django 2.2 on 2019-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0026_auto_20190502_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidomanualidad',
            name='existencias',
            field=models.IntegerField(default=0),
        ),
    ]
