# Generated by Django 2.2 on 2019-05-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0027_contenidomanualidad_existencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='mensaje',
            field=models.TextField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
