# Generated by Django 2.2 on 2019-05-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0028_donacion_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='mensaje',
        ),
    ]
