# Generated by Django 2.2 on 2019-05-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0029_remove_donacion_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='mensaje',
            field=models.TextField(default='', max_length=150),
        ),
    ]
