# Generated by Django 2.2 on 2019-05-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0030_donacion_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidomanualidad',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
