# Generated by Django 2.2 on 2019-05-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0033_auto_20190503_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='manualidad',
            new_name='manu',
        ),
        migrations.RenameField(
            model_name='contenidomanualidad',
            old_name='calificacion',
            new_name='canticomp',
        ),
        migrations.AddField(
            model_name='contenidomanualidad',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
