# Generated by Django 2.2 on 2019-05-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0035_auto_20190507_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infolibro',
            name='formato',
        ),
    ]
