# Generated by Django 2.2 on 2019-05-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0038_infolibro_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='competencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escritor', models.BooleanField(default=False)),
                ('Pintor', models.BooleanField(default=False)),
                ('Escultor', models.BooleanField(default=False)),
                ('Cantante', models.BooleanField(default=False)),
                ('Guitarrista', models.BooleanField(default=False)),
                ('Bajista', models.BooleanField(default=False)),
                ('Pianista', models.BooleanField(default=False)),
                ('Baterista', models.BooleanField(default=False)),
                ('Violinista', models.BooleanField(default=False)),
                ('Saxofonista', models.BooleanField(default=False)),
                ('Acordeonista', models.BooleanField(default=False)),
                ('Trompetista', models.BooleanField(default=False)),
                ('Fotografo', models.BooleanField(default=False)),
                ('Actor', models.BooleanField(default=False)),
            ],
        ),
    ]
