# Generated by Django 2.2 on 2019-05-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0040_auto_20190508_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aficion',
        ),
    ]
