# Generated by Django 2.2 on 2019-05-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0043_auto_20190508_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidomanualidad',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
