# Generated by Django 2.2 on 2019-05-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0045_auto_20190509_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotarjeta',
            name='nombreTitular',
            field=models.CharField(max_length=2),
        ),
    ]
