# Generated by Django 2.2 on 2019-05-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0047_auto_20190509_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotarjeta',
            name='codigoSeguridad',
            field=models.IntegerField(max_length=1),
        ),
    ]
