# Generated by Django 2.2 on 2019-05-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0048_auto_20190509_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='califi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contenidomanualidad',
            name='precioV',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infotarjeta',
            name='codigoSeguridad',
            field=models.PositiveIntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='infotarjeta',
            name='numeroTarjeta',
            field=models.PositiveIntegerField(max_length=8),
        ),
    ]
