# Generated by Django 2.2 on 2019-05-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0050_auto_20190509_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotarjeta',
            name='codigoSeguridad',
            field=models.PositiveIntegerField(),
        ),
    ]
