# Generated by Django 2.2 on 2019-05-10 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0051_auto_20190509_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotarjeta',
            name='numeroTarjeta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
