# Generated by Django 2.2 on 2019-05-10 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0053_auto_20190509_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotarjeta',
            name='anoExpiracion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='infotarjeta',
            name='mesExpiracion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='infotarjeta',
            name='numeroTarjeta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(9000000000000000), django.core.validators.MaxValueValidator(9000000000000000)]),
        ),
    ]
