# Generated by Django 2.2 on 2019-05-10 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0054_auto_20190509_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotarjeta',
            name='apellidoTitular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='infotarjeta',
            name='nombreTitular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='infotarjeta',
            name='numeroTarjeta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9000000000000000)]),
        ),
    ]
