# Generated by Django 2.2 on 2019-05-10 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0055_auto_20190510_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotarjeta',
            name='anoExpiracion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(19), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
