# Generated by Django 2.2 on 2019-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0056_auto_20190510_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidomanualidad',
            name='escultura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenidomanualidad',
            name='pintura',
            field=models.BooleanField(default=False),
        ),
    ]
