# Generated by Django 2.2 on 2019-05-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0057_auto_20190513_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoManualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escultura', models.BooleanField(default=False)),
                ('pintura', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='contenidomanualidad',
            name='escultura',
        ),
        migrations.RemoveField(
            model_name='contenidomanualidad',
            name='pintura',
        ),
        migrations.AddField(
            model_name='contenidomanualidad',
            name='tipo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.TipoManualidad'),
        ),
    ]
