# Generated by Django 2.2 on 2019-05-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0058_auto_20190513_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidomanualidad',
            name='tipo',
            field=models.CharField(choices=[('es', 'escultura'), ('pin', 'pintura')], default='es', max_length=2),
        ),
        migrations.DeleteModel(
            name='TipoManualidad',
        ),
    ]
