# Generated by Django 2.2 on 2019-05-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0060_auto_20190513_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidomanualidad',
            name='tipo',
            field=models.CharField(choices=[('es', 'escultura'), ('pi', 'pintura')], max_length=2, null=True),
        ),
    ]
