# Generated by Django 2.2 on 2019-05-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0062_auto_20190513_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generoBusqueda', models.CharField(blank=True, max_length=30)),
                ('usuarioBuscador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.infousuario')),
            ],
        ),
    ]
