# Generated by Django 2.2 on 2019-05-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0063_busquedastring'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comedia', models.BooleanField(default=False)),
                ('Drama', models.BooleanField(default=False)),
                ('Retrato', models.BooleanField(default=False)),
                ('Terror', models.BooleanField(default=False)),
                ('Accion', models.BooleanField(default=False)),
                ('Belico', models.BooleanField(default=False)),
                ('CienciaFiccion', models.BooleanField(default=False)),
                ('Aventura', models.BooleanField(default=False)),
                ('DelOeste', models.BooleanField(default=False)),
                ('ArtesMarciales', models.BooleanField(default=False)),
                ('Fantastico', models.BooleanField(default=False)),
                ('Suspenso', models.BooleanField(default=False)),
                ('Historico', models.BooleanField(default=False)),
                ('Adolescente', models.BooleanField(default=False)),
                ('Infantil', models.BooleanField(default=False)),
                ('Político_Social', models.BooleanField(default=False)),
                ('Animacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contenidomultimedia',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.GeneroMultimedia'),
        ),
    ]
