# Generated by Django 2.2 on 2019-05-18 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homePage', '0064_auto_20190517_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Cuerpo', models.TextField(max_length=150)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Emisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_Emisor', to=settings.AUTH_USER_MODEL)),
                ('Receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_Pasivo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_Activo', to=settings.AUTH_USER_MODEL)),
                ('Pasivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_Pasivo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
