# Generated by Django 2.2 on 2019-05-18 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0066_comentarioobraliteraria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infousuario',
            old_name='es_Nada',
            new_name='es_Colaborador',
        ),
        migrations.AlterField(
            model_name='comentarioobraliteraria',
            name='califi',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0, 0)]),
        ),
    ]
