# Generated by Django 2.2.1 on 2019-05-20 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homePage', '0067_auto_20190518_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorOfrecido', models.PositiveIntegerField(default=0)),
                ('Titulo', models.CharField(max_length=50)),
                ('Cuerpo', models.TextField(max_length=150)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Emisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_Emisor', to=settings.AUTH_USER_MODEL)),
                ('Receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_Pasivo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
