# Generated by Django 2.2 on 2019-05-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0069_auto_20190521_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidomanualidad',
            name='imagen3',
            field=models.ImageField(blank=True, default='images/manualidades/covers/default.jpg', null=True, upload_to='images/manualidades/covers/'),
        ),
    ]
