# Generated by Django 2.2 on 2019-05-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0072_infousuario_tienecuentaactivada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infousuario',
            name='tieneCuentaActivada',
        ),
        migrations.AddField(
            model_name='infolibro',
            name='tieneCuentaActivada',
            field=models.BooleanField(default=True),
        ),
    ]
