# Generated by Django 2.1.8 on 2019-05-22 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0074_auto_20190522_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('califi', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0, 0)])),
                ('comentario', models.TextField(default='', max_length=150)),
                ('usuarioComentador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.infousuario')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.contenidoMultimedia')),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='califi',
            field=models.PositiveIntegerField(),
        ),
    ]
