# Generated by Django 2.1.8 on 2019-05-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0077_carrito_multimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradores',
            name='multimedia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.contenidoMultimedia'),
        ),
    ]
