# Generated by Django 2.2 on 2019-05-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0079_infousuario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuario',
            name='numeroTelefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
