# Generated by Django 2.2 on 2019-05-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0081_auto_20190522_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='numeroTelefono',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
