# Generated by Django 2.2 on 2019-05-22 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0082_auto_20190522_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='numeroTelefono',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
