# Generated by Django 2.2 on 2019-05-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0083_auto_20190522_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuario',
            name='cuantaCerrada',
            field=models.BooleanField(default=False),
        ),
    ]
