# Generated by Django 2.2 on 2019-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0084_infousuario_cuantacerrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=130, null=True),
        ),
    ]
